pool:
  vmImage: 'windows-latest'

variables:
  solution: $(Build.SourcesDirectory)/TranslucentTB.sln

strategy:
  matrix:
    'ARM64 Debug':
      configuration: Debug
      platform: ARM64
    'ARM64 Release':
      configuration: Release
      platform: ARM64
    'x64 Debug':
      configuration: Debug
      platform: x64
    'x64 Release':
      configuration: Release
      platform: x64

steps:
- script: vcpkg integrate install
  displayName: 'Integrate vcpkg'
- script: vcpkg install --triplet $(platform)-windows fmt gtest spdlog
  displayName: 'Install vcpkg dependencies'
- script: vcpkg install --triplet $(platform)-windows --overlay-ports=$(Build.SourcesDirectory)/ports --head detours member-thunk rapidjson wil
  displayName: 'Install vcpkg head dependencies'
- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: $(solution)
- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: $(solution)
    platform: $(platform)
    configuration: $(configuration)
