pool:
  vmImage: 'windows-latest'

variables:
  solution: $(Build.SourcesDirectory)/TranslucentTB.sln
  vcpkgLocation: $(Build.BinariesDirectory)/vcpkg
  vcpkgVersion: 2020.07

strategy:
  matrix:
    'ARM64 Debug':
      configuration: Debug
      platform: ARM64
    'ARM64 Release':
      configuration: Release
      platform: ARM64
    'x64 Debug':
      configuration: Debug
      platform: x64
    'x64 Release':
      configuration: Release
      platform: x64

steps:
- task: run-vcpkg@0
  displayName: 'Install vcpkg dependencies'
  inputs:
    vcpkgArguments: fmt gtest spdlog
    vcpkgDirectory: $(vcpkgLocation)
    vcpkgGitCommitId: $(vcpkgVersion)
    vcpkgTriplet: $(platform)-windows
- task: run-vcpkg@0
  displayName: 'Install vcpkg overlay dependencies'
  inputs:
    vcpkgArguments: detours member-thunk --overlay-ports=$(Build.SourcesDirectory)/ports
    vcpkgDirectory: $(vcpkgLocation)
    vcpkgGitCommitId: $(vcpkgVersion)
    vcpkgTriplet: $(platform)-windows
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'
- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: $(solution)
- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: $(solution)
    platform: $(platform)
    configuration: $(configuration)
