pool:
  vmImage: 'windows-2022'

trigger:
  tags:
    include:
    - '*'

steps:
- template: templates/build.yml
  parameters:
    platform: x64
    configuration: Release
    buildType: Release
- powershell: $(Build.SourcesDirectory)/.azp/scripts/create-portable.ps1 -Platform x64 -Configuration Release -WorkDir "$(Pipeline.Workspace)" -OutputDir "$(Build.ArtifactStagingDirectory)" -NoConfig
  displayName: Create x64 portable build
- powershell: $(Build.SourcesDirectory)/.azp/scripts/create-portable.ps1 -Platform ARM64 -Configuration Release -WorkDir "$(Pipeline.Workspace)" -OutputDir "$(Build.ArtifactStagingDirectory)" -NoConfig
  displayName: Create ARM portable build
# TODO: copy msixbundle and appxsym
# TODO: create GH release draft.
