pool:
  vmImage: 'windows-2022'

trigger:
  tags:
    include:
    - '*'

steps:
- template: templates/build.yml
  parameters:
    platform: x64
    configuration: Release
    signBuild: true
    buildType: Release
# TODO: upload msixupload to the store (or artifacts), zip up portable release and create GH release draft.
